version: 2.1

executors:
  android-flutter:
    docker:
      - image: gmemstr/flutter-fastlane:latest
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'
      
jobs:
  build:
    executor: android-flutter
    steps:
      - checkout
      #- run: flutter channel stable
      #- run: git remote set-url origin git@github.com:flutter/flutter.git
      #- run: git clone https://github.com/flutter/flutter.git -b stable
      #- run: export PATH="$PATH:`pwd`/flutter/bin"
      #- run: flutter doctor
      #- run: flutter build apk
      - run: sudo gem install fastlane
      - run: sudo gem install bundle
      - run: ls && cd android && ls
      - run: fastlane init

workflows:
  deploy:
    jobs:
      - build
