version: 2.1

executors:
  android-flutter:
    docker:
      - image: gmemstr/flutter-fastlane-android:29.0
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'
     
jobs:
  beta_deploy:
    executor: android-flutter
    steps:
      - checkout
      - flutter run android
